version: "1"
type: "docker-compose"
dockerComposeFile: "docker-compose.coolify.yml"
dockerComposeFileLocation: "."
services:
  - name: "backend"
    domains:
      - "business-scraper.coolify.app"
  - name: "frontend" 
    domains:
      - "business-scraper.coolify.app"
