version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: business-scraper-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: business123
      MONGO_INITDB_DATABASE: business_scraper
    ports:
      - "27017:27017"  # Expose MongoDB port for external access
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data:
